In [58]:
# Define the documents as a dictionary where keys are document titles and values are document content
documents = {
    "Article: Pandas Basics": "This article covers the basics of using Pandas in Python.",
    "Tutorial: Data Visualization": "Learn about data visualization techniques with Python libraries.",
    "Case Study: Sales Analysis": "Analyze sales data using Python for a real-world case study."
}

In [59]:
# get the keys of the documents and store it in the list
key_documents = list(documents.keys())

# display the list of the key documents
print(key_documents)

['Article: Pandas Basics', 'Tutorial: Data Visualization', 'Case Study: Sales Analysis']


In [60]:
# Extract the category of the key documents and store it

In [61]:
# Extract the content values and put them in a list
document_content_list = list(documents.values())

# Display the list of document content
print(document_content_list)

['This article covers the basics of using Pandas in Python.', 'Learn about data visualization techniques with Python libraries.', 'Analyze sales data using Python for a real-world case study.']


In [62]:
# Gather the set of all unique terms from the list content of document and diplay the result
unique_terms = {term for doc in document_content_list for term in doc.split()}
unique_terms

{'Analyze',
 'Learn',
 'Pandas',
 'Python',
 'Python.',
 'This',
 'a',
 'about',
 'article',
 'basics',
 'case',
 'covers',
 'data',
 'for',
 'in',
 'libraries.',
 'of',
 'real-world',
 'sales',
 'study.',
 'techniques',
 'the',
 'using',
 'visualization',
 'with'}

In [63]:
# create a matrix for the document by using the unique term
doc_term_matrix = {}

# your code here
for term in unique_terms:
    doc_term_matrix[term] = []
    for doc in document_content_list:
        if term in doc:
            doc_term_matrix[term].append(1)
        else: doc_term_matrix[term].append(0)


# display the result of the matrix
doc_term_matrix

{'basics': [1, 0, 0],
 'Python': [1, 1, 1],
 'sales': [0, 0, 1],
 'for': [0, 0, 1],
 'with': [0, 1, 0],
 'This': [1, 0, 0],
 'case': [0, 0, 1],
 'visualization': [0, 1, 0],
 'a': [1, 1, 1],
 'in': [1, 0, 1],
 'real-world': [0, 0, 1],
 'the': [1, 0, 0],
 'libraries.': [0, 1, 0],
 'about': [0, 1, 0],
 'article': [1, 0, 0],
 'Learn': [0, 1, 0],
 'using': [1, 0, 1],
 'Pandas': [1, 0, 0],
 'data': [0, 1, 1],
 'covers': [1, 0, 0],
 'Analyze': [0, 0, 1],
 'Python.': [1, 0, 0],
 'study.': [0, 0, 1],
 'techniques': [0, 1, 0],
 'of': [1, 0, 0]}

In [64]:
# import the numpy library if it doesn't work you need to install numpy
import numpy as np

docs_array = np.array(document_content_list, dtype='object')

v1 = np.array(doc_term_matrix['Learn'])    
v2 = np.array(doc_term_matrix['Python'])

print(v1)
print(v2)
print('-------')
# find the document for those have at least one word
v3 = v1 & v2

print(v3)

# display the content document from the result
[doc for doc in v3 * docs_array if doc]

[0 1 0]
[1 1 1]
-------
[0 1 0]


['Learn about data visualization techniques with Python libraries.']

In [65]:
# import the numpy library if it doesn't work you need to install numpy
import numpy as np

docs_array = np.array(document_content_list, dtype='object')

v1 = np.array(doc_term_matrix['Learn'])    
v2 = np.array(doc_term_matrix['Python'])

print(v1)
print(v2)
print('-------')
# find the document for those have at least one word
v3 = v1 | v2

print(v3)

# display the content document from the result
[doc for doc in v3 * docs_array if doc]

[0 1 0]
[1 1 1]
-------
[1 1 1]


['This article covers the basics of using Pandas in Python.',
 'Learn about data visualization techniques with Python libraries.',
 'Analyze sales data using Python for a real-world case study.']