In [3]:
import pandas as pd
file = pd.read_csv(r"C:\Users\SO KIMLANG\Downloads\Telegram Desktop\tdoc.csv",header = None)
file

0                                                  1
0  Document 1  This is the first document. It contains some w...
1  Document 2  The second document is a bit longer and has di...
2  Document 3  The third document is short. Short documents c...

In [4]:
file.iloc[1][0]

'Document 2'

In [5]:
file.iloc[:,1].tolist()

['This is the first document. It contains some words.',
 'The second document is a bit longer and has different words.',
 'The third document is short. Short documents can be concise.']

In [6]:
# to change the name of the column
file.columns = ["a", "b"]
file

a                                                  b
0  Document 1  This is the first document. It contains some w...
1  Document 2  The second document is a bit longer and has di...
2  Document 3  The third document is short. Short documents c...

In [7]:
file["b"].tolist()

['This is the first document. It contains some words.',
 'The second document is a bit longer and has different words.',
 'The third document is short. Short documents can be concise.']

In [8]:
col1 = file["a"].tolist()
list1 = list(col1)
list1

['Document 1', 'Document 2', 'Document 3']

In [9]:
col2 = file["b"].tolist()
list2 = list(col2)
list2

['This is the first document. It contains some words.',
 'The second document is a bit longer and has different words.',
 'The third document is short. Short documents can be concise.']

In [10]:
unique_terms = {term for doc in list2 for term in doc.split()}
unique_terms

{'It',
 'Short',
 'The',
 'This',
 'a',
 'and',
 'be',
 'bit',
 'can',
 'concise.',
 'contains',
 'different',
 'document',
 'document.',
 'documents',
 'first',
 'has',
 'is',
 'longer',
 'second',
 'short.',
 'some',
 'the',
 'third',
 'words.'}

In [11]:
doc_term_matrix = {}

# your code here
for term in unique_terms:
    doc_term_matrix[term] = []
    for doc in list2:
        if term in doc:
            doc_term_matrix[term].append(1)
        else: doc_term_matrix[term].append(0)


# display the result of the matrix
doc_term_matrix

{'be': [0, 0, 1],
 'can': [0, 0, 1],
 'a': [1, 1, 1],
 'words.': [1, 1, 0],
 'contains': [1, 0, 0],
 'The': [0, 1, 1],
 'some': [1, 0, 0],
 'second': [0, 1, 0],
 'and': [0, 1, 0],
 'longer': [0, 1, 0],
 'documents': [0, 0, 1],
 'is': [1, 1, 1],
 'Short': [0, 0, 1],
 'the': [1, 0, 0],
 'has': [0, 1, 0],
 'different': [0, 1, 0],
 'short.': [0, 0, 1],
 'This': [1, 0, 0],
 'document': [1, 1, 1],
 'third': [0, 0, 1],
 'bit': [0, 1, 0],
 'first': [1, 0, 0],
 'concise.': [0, 0, 1],
 'It': [1, 0, 0],
 'document.': [1, 0, 0]}

In [12]:
import numpy as np

docs_array = np.array(list2, dtype='object')

v1 = np.array(doc_term_matrix['words.'])    
v2 = np.array(doc_term_matrix['first'])

print(v1)
print(v2)
print('-------')
# find the document for those have at least one word
v3 = v1 | v2

print(v3)

# display the content document from the result
[doc for doc in v3 * docs_array if doc]

[1 1 0]
[1 0 0]
-------
[1 1 0]


['This is the first document. It contains some words.',
 'The second document is a bit longer and has different words.']

In [13]:
import csv
#name of csv file
csv_file = "unique_term.csv"

In [14]:
#open the csv dile in write mode
with open(csv_file, mode='w', newline='') as file:
    writer = csv.writer(file)
    #write data from the set to the csv file
    for term in unique_terms:
        writer.writerow([term])

In [15]:
print(f"CSV file '{csv_file}' has been created with set data.")

CSV file 'unique_term.csv' has been created with set data.
